#pragma once

// Copy this file to local_config.h, then replace the placeholder values locally.
// local_config.h is intentionally ignored by Git.

#define CERION_WIFI_SSID "REPLACE_WITH_WIFI_SSID"
#define CERION_WIFI_PASSWORD "REPLACE_WITH_WIFI_PASSWORD"

// CERION uses this existing Firebase project. The ESP32 does not need a
// Firebase Web API key because it authenticates to the ingestion Function with
// a per-device key generated by the CERION Devices screen.
#define CERION_FIREBASE_PROJECT_ID "cerion-platform"
#define CERION_INGEST_URL \
  "https://asia-southeast1-cerion-platform.cloudfunctions.net/ingestReading"
#define CERION_DEVICE_ID "REPLACE_WITH_FIRESTORE_DEVICE_ID"
#define CERION_DEVICE_KEY "REPLACE_WITH_ONE_TIME_DEVICE_SECRET"
#define CERION_FIRMWARE_VERSION "1.0.0"

#define CERION_UPLOAD_INTERVAL_MS 10000UL
#define CERION_OFFLINE_BUFFER_CAPACITY 60

#define CERION_WIFI_CONNECT_TIMEOUT_MS 15000UL
#define CERION_WIFI_RETRY_INITIAL_MS 2000UL
#define CERION_WIFI_RETRY_MAX_MS 60000UL
#define CERION_BACKEND_RETRY_INITIAL_MS 2000UL
#define CERION_BACKEND_RETRY_MAX_MS 60000UL
#define CERION_HTTP_TIMEOUT_MS 15000UL

#define CERION_NTP_SERVER_1 "time.google.com"
#define CERION_NTP_SERVER_2 "pool.ntp.org"
#define CERION_NTP_SERVER_3 "time.cloudflare.com"

// Enable only sensors physically installed on this device. Disabled or failed
// sensors are omitted from the JSON; the firmware never creates substitute data.
#define CERION_ENABLE_BME688 1
#define CERION_ENABLE_PZEM004T 1

#define CERION_I2C_SDA_PIN 21
#define CERION_I2C_SCL_PIN 22
#define CERION_BME688_I2C_ADDRESS 0x76

// PZEM UART wiring: ESP32 RX receives PZEM TX; ESP32 TX drives PZEM RX.
#define CERION_PZEM_RX_PIN 16
#define CERION_PZEM_TX_PIN 17
