[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.embed_txtfiles = data/gts-roots.pem
lib_deps =
  bblanchon/ArduinoJson@^7.4.3
  adafruit/Adafruit BME680 Library@^2.0.5
  mandulaj/PZEM-004T-v30@^1.1.2
build_flags =
  -Wall
  -Wextra
  -Werror=return-type

